[package]
name = "clip-squeezer"
version = "0.2.1"
description = "Clip Squeezer"
authors = ["Rory Kingan"]
license = "GPL-3.0-or-later"
edition = "2021"

[lib]
name = "clip_squeezer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
same-file = "1.0.6"
tokio = { version = "1", features = ["full"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
